spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://viaduct.proxy.rlwy.net:22304/railway"
    username: '${MYSQLUSER}'
    password: '${MYSQL_ROOT_PASSWORD}'
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
          #sql:
          #init:
        #mode:always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
server:
      port: 3306

