spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: '${DB_url}'
    username: '${DB_username}'
    password: '${DB_password}'
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 3306

