spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/tech_buy"
    username: root
    password: 03121977852852QaZ!
  jpa:
    hibernate:
      ddl-auto: update